I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/minigame_pe.rpy", line 53, in script
    if answer_q1 != None:
  File "game/minigame_pe.rpy", line 53, in <module>
    if answer_q1 != None:
NameError: name 'answer_q1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/minigame_pe.rpy", line 53, in script
    if answer_q1 != None:
  File "D:\Programy\renpy-6.99.12.4-sdk\renpy\ast.py", line 1656, in execute
    if renpy.python.py_eval(condition):
  File "D:\Programy\renpy-6.99.12.4-sdk\renpy\python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Programy\renpy-6.99.12.4-sdk\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/minigame_pe.rpy", line 53, in <module>
    if answer_q1 != None:
NameError: name 'answer_q1' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Wonderful Time 1.0
